using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;

namespace CC.Utilities
{
    public static class FontBuilder
    {
        // ReSharper disable InconsistentNaming
        private const string ARGUMENT_EXCEPTION_TEXT = "Invalid string supplied. Input string must come from Font.ToString() or Font.ToStringEx()\r\n\r\n{0}";
        // ReSharper restore InconsistentNaming

        /// <summary>
        /// Created a System.Drawing.Font from a string generated by either System.Drawing.Font.ToString() or System.Drawing.Font.ToStringEx()
        /// </summary>
        /// <param name="fontString">The string to build the System.Drawing.Font from</param>
        /// <returns>A System.Drawing.Font object</returns>
        public static Font FromString(string fontString)
        {
            Font retVal = null;

            if (fontString.StartsWith("[Font: ") && fontString.EndsWith("]"))
            {

                fontString = fontString.Remove(0, 7);
                fontString = fontString.Remove(fontString.Length - 1, 1);

                string[] parameters = fontString.Split(new char[] {','});
                Dictionary<string, string> fontParameters = new Dictionary<string, string>();

                foreach (string parameter in parameters)
                {
                    string[] keyValue = parameter.Trim().Split(new char[] {'='});
                    if (keyValue.Length == 2)
                    {
                        //Logging.LogMessage(keyValue[0] + " == " + keyValue[1]);
                        fontParameters.Add(keyValue[0], keyValue[1]);
                    }
                }

                switch (fontParameters.Count)
                {
                    case 5: // This is the only one I need for ToString() I believe ...
                        {
                            if (fontParameters.ContainsKey("Name") && fontParameters.ContainsKey("Size") && fontParameters.ContainsKey("Units") && fontParameters.ContainsKey("GdiCharSet") && fontParameters.ContainsKey("GdiVerticalFont"))
                            {
                                retVal = new Font(fontParameters["Name"], float.Parse(fontParameters["Size"]), FontStyle.Regular, (GraphicsUnit)int.Parse(fontParameters["Units"]), byte.Parse(fontParameters["GdiCharSet"]), bool.Parse(fontParameters["GdiVerticalFont"]));
                            }
                            else
                            {
                                throw new ArgumentException(string.Format(ARGUMENT_EXCEPTION_TEXT, fontString), "fontString");
                            }
                            break;
                        }
                    case 6: // This is the only one I need for ToStringEx() (for now...)
                        {
                            if (fontParameters.ContainsKey("Name") && fontParameters.ContainsKey("Size") && fontParameters.ContainsKey("Units") && fontParameters.ContainsKey("GdiCharSet") && fontParameters.ContainsKey("GdiVerticalFont") && fontParameters.ContainsKey("Style"))
                            {
                                retVal = new Font(fontParameters["Name"], float.Parse(fontParameters["Size"]), (FontStyle) int.Parse(fontParameters["Style"]), (GraphicsUnit) int.Parse(fontParameters["Units"]), byte.Parse(fontParameters["GdiCharSet"]), bool.Parse(fontParameters["GdiVerticalFont"]));
                            }
                            else
                            {
                                throw new ArgumentException(string.Format(ARGUMENT_EXCEPTION_TEXT, fontString), "fontString");                                
                            }
                            break;
                        }
                    default:
                        {
                            throw new ArgumentException(string.Format(ARGUMENT_EXCEPTION_TEXT, fontString), "fontString");
                        }
                }
            }
            else
            {
                throw new ArgumentException(string.Format(ARGUMENT_EXCEPTION_TEXT, fontString), "fontString");
            }

            return retVal;
        }

        /// <summary>
        /// Extends the Font.ToString() method for parameters that are not included
        /// </summary>
        /// <param name="font">The System.Drawing.Font to convert to a string</param>
        /// <returns>Returns a human readable representation of this System.Drawing.Font</returns>
        public static string ToStringEx(this Font font)
        {
            StringBuilder returnValue = new StringBuilder();

            returnValue.Append(font.ToString());
            returnValue.Remove(returnValue.Length - 1, 1);
            if (font.Style != FontStyle.Regular)
            {
                returnValue.Append(", Style=" + (int) font.Style);
            }
            returnValue.Append("]");

            return returnValue.ToString();
        }
    }
}
